version: '3.3'



services:

  app:
    image: calebf/simple-mailer:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 8000:80

  dev:
    image: calebf/simple-mailer:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    env_file: .env
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    ports:
      - 8000:8000